version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./app
    ports:
      - "5000:5000"


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - flask_app